### PR TITLE
Migrate netcoreapp3.1 and ILogger

### PR DESCRIPTION
**Pull request by TsuyoshiUshio**
Currently, the app is written against netcoreapp2.2 that is no longer supported. 
@pragnagopa 

https://github.com/Azure-App-Service/KuduLite/issues/202

I start this PR for discussing the design. 

The process might be the following, however, I need to learn more to validate it. 

- [x] Update netcoreapp3.1 with removing all the errors
- [x] Run CI to see if the all test works correctly (How can we run the CI? @sanchitmehta do you know ?)
- [x] Test with k4apps (By performing zip deploy)
- [ ] Remove unnecessary classes. (e.g. DebugExtensionMiddleWares.cs looks no reference)
- [ ] Enable Console Logging for ASP.NET
- [ ] Remove ITracer and migrate to ILogger
- [ ] Adding more logs for enable debugging on the Lima

### CODE REVIEW

**Comment by pragnagopa** [comment]
Thanks for the PR! I  agree with the approach you described. I recommend sending separate PRs. So this PR can be merged as it is scoped to moving to .Net Core 3.1 @sanchitmehta  what do you think?

**Comment by TsuyoshiUshio** [comment]
I agree with you @pragnagopa ! 
Hi @sanchitmehta  I'm wondering how we can execute this CI against `feature/k8se` branch ?

**Comment by TsuyoshiUshio** [comment]
Hi @sanchitmehta 

I update the testing, by following rules. However, I sometimes, wondering if my fix is correct. (I don't know the detail usage of [Oryx build](https://github.com/microsoft/Oryx) ) and don't know the context of this test. Could you have a look at my change is correct or not. 

Since the Oryx Build is fails a lot. It looks some feature change but not updated the unit tests. 
So that I trust the current code is correct. However, some tests are probably not used and probably wrong. I add `TODO` comments for these tests. 

CC @pragnagopa

**Comment by TsuyoshiUshio** [comment]
Hi @Hazhzeng 
Could you help me to review this PR against feature/k8se branch? 
The branch has a lot of broken test about the oryx build. I currently, change the test code. Some of them I don't have confidence if it is correct since I don't know about current oryx build usage. (Now I'm trying to learn the usage) However, it might be good for reviewed by someone who is an expert about it.

**Comment by TsuyoshiUshio** [comment]
Hi @pragnagopa @sanchitmehta 

I tested with this change deploy with zip deploy and container app it works. 
I'm wondering if we need to test other use cases like WebApp or good to go? If it is ok, Let get merged! I'll update the PR of the k4apps side.

**Comment by TsuyoshiUshio** [comment]
The next PR will be adding more logs and switch it into ILogger.

**Review by pragnagopa — APPROVED** [review]

**Comment by sanchitmehta** [comment]
Needs a fix for Local Git Deploys as well: https://github.com/Azure-App-Service/KuduLite/blob/d4bb543f70026fa87a6975c5eb9ff9c5fa350355/Kudu.Core/SourceControl/Git/KnownEnvironment.cs#L17 . This is the post recieve hook that we create for Local Git. It needs to refer the self-contained binary

**Comment by TsuyoshiUshio** [comment]
Hi @sanchitmehta 
That is a very good catch! I also find other places that requires to change (probably not used) also change the unit testing to fit it. 

I also build the image with this version and tested with lima arc cluster. It works.

**Review by sanchitmehta — APPROVED** [review]

**Pull request merged**
